export const ADD_TO_LIST = 'ADD_TO_LIST'
export const CHECKOUT_REQUEST = 'CHECKOUT_REQUEST'
export const CHECKOUT_SUCCESS = 'CHECKOUT_SUCCESS'
export const CHECKOUT_FAILURE = 'CHECKOUT_FAILURE'
export const RECEIVE_PRODUCTS = 'RECEIVE_PRODUCTS'


export const UPDATE_USER_INFO = 'UPDATE_USER_INFO'
export const ADD_TO_MEMBER_LIST = 'ADD_TO_MEMBER_LIST'
export const UPDATE_MSG_INDEX = 'UPDATE_MSG_INDEX'

